id: IECD0F900
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:20:11+00:00'
last_modified: '2022-06-08T06:54:45.034509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16719
  title: གདན་རབས་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    22B4:
      image_group_id: I2PD18889
      title: ''
      total_pages: 190
      order: 1
      base_file: 22B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
